name: "Bug Report"
description: "Create a report to help us improve"
labels: [bug]
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is. Please include the exact version of Visual Studio / Rider/ other IDE (or command line), and exactly what target framework(s) it fails on."
      placeholder: |
        Using Visual Studio / Rider / VSCode / the command line (and the exact version of the IDE), I was targetting the following Frameworks: [x,y,z]
        Anything else that you think might be useful.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to reproduce"
      description: "A link to some code to reproduce the bug can speed up a fix. Alternatively, show steps to reproduce the behaviour."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
